[package]
name = "shader_try"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = { path = "crates/spirv-std", features = ["glam"] }
[target.'cfg(not(target_arch = "spirv"))'.dependencies]
rayon = "1.5"
